POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json 

{
    "username":"naringles",
	"email":"naringles@gmail.com",
	"password":"abCdef"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json 

{
	"email":"naringles@gmail.com",
	"password":"abCdef"
}

###
GET http://localhost:3000/user/data HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMxODNhZWQwMjk3MzZiZTAwODliMDciLCJpYXQiOjE1OTcwOTM4NjZ9.tbPPxGCjJhx_K7SLnXGiYIUI6L9_1VHGCSUQ-_Vv3o0
content-type: application/json 
	
	
